### ISSUE TITLE
crypto_stream_chacha20_xor seems not be exposed

### ISSUE THREAD

**Issue by Jeyhey** [terl/lazysodium-android#10]
I am trying to use the function `crypto_stream_chacha20_xor` of libsodium but can't find it. Is there a way to use this function?

**Comment by gurpreet-** [comment]
Hello @Jeyhey 

This is one of two things left to do on my [features list](https://docs.lazycode.co/lazysodium/features). It's not been implemented yet because I had some trouble with stream ciphers on Android and resolved to implement them later.

I will try and get these last features done tonight.

**Comment by Jeyhey** [comment]
That was fast : )! Thank you!
