### ISSUE TITLE
File Encrypting in php and decrypting in android (java)

### ISSUE THREAD

**Issue by Hosseinyzr** [terl/lazysodium-android#12]
Hi, thanks for this library.
I want to encrypt **files** in **php** , download them and decrypt them in **android** (with java).

encryption and decryption in android has no problem with this functions:
cryptoAeadXChaCha20Poly1305IetfEncrypt(....);
cryptoAeadXChaCha20Poly1305IetfDecrypt(....);

and every thing is fine. but I wonder how to encrypt in php and decrypt in java or vice versa.
the key is generated according to a contract between client and server side , and both we know what it is.
but as i found the cilent should get nonce from server side. so how to do it securely?
and is that **xchacha20** safe and approprite?
so the general question : how to encrypt in php and decrypt on android securely ans fast.
thanks...

**Comment by gurpreet-** [comment]
Hello @Hosseinyzr,

Yes you can use `cryptoAeadXChaCha20Poly1305IetfEncrypt`, but why not use the [SecretBox](https://download.libsodium.org/doc/secret-key_cryptography/authenticated_encryption) functions? The SecretBox functions take a key which you can use to encrypt/decrypt your files.

To get your nonce from server to client, send it securely via an SSL encrypted network connection. You don't even need to securely send it. It's a public nonce so you can send it via an unencrypted network  connection too.

**Comment by Hosseinyzr** [comment]
@gurpreet-  Thanks! it worked!
just some questions? As I know secretbox uses salsa algorithm , is it safe enough  compare to xchacha?
and another: is it safe to generate our own key with some parameter , for example two string that both side knows it, then generate a password?
sorry if my question is not so proffessional...

**Comment by gurpreet-** [comment]
If you are encrypting files you should use [SecretStream](https://libsodium.gitbook.io/doc/secret-key_cryptography/secretstream) instead of SecretBox. It's more low-level than SecretBox, but it encrypts securely and swiftly.

With regards to the `sodium_crypto_secretbox` function only taking in strings, you must note that all files are just bytes so you could simply encode those bytes into a string representation using an encoder like Base64 or Hexadecimal then encrypt. Then when you decrypt, just remember to decode the string.

So something like:

```sh
Server:
File -> Encode -> Encrypt

Client:
Decrypt -> Decode -> File
```

**Comment by Hosseinyzr** [comment]
@gurpreet-  Great! Thank you...
